# Generated by Django 6.0.3 on 2026-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, help_text='11-digit Bank Verification Number', max_length=11, null=True, unique=True, verbose_name='BVN'),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn_verified',
            field=models.BooleanField(default=False, verbose_name='BVN Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, help_text='11-digit National Identification Number', max_length=11, null=True, unique=True, verbose_name='NIN'),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_verified',
            field=models.BooleanField(default=False, verbose_name='NIN Verified'),
        ),
    ]
