# Generated by Django 5.2.8 on 2026-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_otp_in_response', models.BooleanField(default=True, help_text='Return the OTP code in the register / send-otp response body. Turn OFF in production once an SMS gateway is configured.', verbose_name='Show OTP in API response')),
                ('use_fixed_otp', models.BooleanField(default=True, help_text='Always generate the fixed OTP value below instead of a random code.', verbose_name='Use fixed OTP (testing)')),
                ('fixed_otp_value', models.CharField(default='123456', help_text='The hardcoded OTP used when "Use fixed OTP" is ON. Must be 6 digits.', max_length=6, verbose_name='Fixed OTP value')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Block all financial transactions (VTU, transfers, wallet funding) and return a 503 response with a maintenance message.', verbose_name='Maintenance mode')),
                ('maintenance_message', models.CharField(default='The system is currently under maintenance. Please try again later.', help_text='Message returned to users when maintenance mode is active.', max_length=255, verbose_name='Maintenance message')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
