# Generated by Django 6.0.3 on 2026-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0001_site_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='dev_mode',
            field=models.BooleanField(default=True, help_text='Master toggle. ON = development/testing (OTP shown, fixed OTP active, CORS open). OFF = production (OTP hidden, real random OTPs, strict security). Toggling this automatically updates the OTP settings below.', verbose_name='Development mode'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='show_otp_in_response',
            field=models.BooleanField(default=True, help_text='Return the OTP code in the register / send-otp response body. Automatically disabled when Dev Mode is OFF.', verbose_name='Show OTP in API response'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='use_fixed_otp',
            field=models.BooleanField(default=True, help_text='Always use the fixed OTP value below instead of a random code. Automatically disabled when Dev Mode is OFF.', verbose_name='Use fixed OTP (testing)'),
        ),
    ]
