# Generated by Django 5.2.8 on 2026-03-05 17:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='wallet',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=14),
        ),
    ]
